// ACOES DA TELA BUSCAR
export const BUSCAR_LOADING = 'BUSCAR_LOADING';
export const GET_ADS = 'GET_ADS';
export const LOADING_CHATROOM = 'LOADING_CHATROOM';

// acoes do chat
export const SEND_MSG = 'SEND_MSG';
export const SEND_MSG_ERROR = 'SEND_MSG_ERROR';
export const CHECK_DOC_EXISTS = 'CHECK_DOC_EXISTS';
export const GET_CONVERSATION_LIST = 'GET_CONVERSATION_LIST';
export const GET_CONVERSATION_LIST_TO_DISPLAY = 'GET_CONVERSATION_LIST_TO_DISPLAY';
export const GET_CONVERSATION_HISTORY = 'GET_CONVERSATION_HISTORY';

// Logged Out
export const LOG_IN = 'LOG_IN';
export const SET_LOGGED_IN_STATE = 'SET_LOGGED_IN_STATE';
export const LOADING_LOGOUT = 'LOADING_LOGOUT';

// acoes para cadastro
export const PHONE_SEND_CODE = 'PHONE_SEND_CODE';
export const SENDING_MSG = 'SENDING_MSG';
export const PHONE_CONFIRM_CODE = 'PHONE_CONFIRM_CODE';
export const PHONE_CONFIRM_CODE_ERROR = 'PHONE_CONFIRM_CODE_ERROR';
export const EMAIL_PASS_SIGNUP = 'EMAIL_PASS_SIGNUP';
export const SET_PHONE_NUMBER_STATE = 'SET_PHONE_NUMBER_STATE';
export const RESET_CONFIRMATION_CODE = 'RESET_CONFIRMATION_CODE';
export const SET_NAME_STATE = 'SET_NAME_STATE';
export const SET_NAME = 'SET_NAME';

// CATEGORIAS ACTIONS
export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';

// adicionar contato
export const ADICIONAR_CONTATO = 'ADICIONAR_CONTATO';
export const ADICIONAR_CONTATO_ERRO = 'ADICIONAR_CONTATO_ERRO';
export const MODIFICAR_CELULAR = 'MODIFICAR_CELULAR';

// listar contatos
export const FETCHING_USERS = 'FETCHING_USERS';

// Listening to Firebase firestore
export const LISTEN_FIREBASE = 'LISTEN_FIREBASE';

// REHYDRATE the store
export const REHYDRATE = 'REHYDRATE';

// ACOES DO PERFIL
export const NAME_STATE = 'NAME_STATE';
export const SUCCESSFUL_UPDATED = 'SUCCESSFUL_UPDATED';
export const ERROR_WHILE_UPDATING = 'ERROR_WHILE_UPDATING';
export const UPDATE_TO_PHONESENDCODE = 'UPDATE_TO_PHONESENDCODE';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE';
export const UPDATE_PROF_PIC_DOWNLOAD_URL = 'UPDATE_PROF_PIC_DOWNLOAD_URL';
export const PERFIL_LOADING = 'PERFIL_LOADING';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const COVER_IMAGES = 'COVER_IMAGES';
export const CATALOG_IMAGES = 'CATALOG_IMAGES';
export const AMBIENTE_IMAGES = 'AMBIENTE_IMAGES';
export const MAP_PREVIEW = 'MAP_PREVIEW';
export const REGISTER_BUSINESS = 'REGISTER_BUSINESS';
export const BUSINESS_LOADING = 'BUSINESS_LOADING';
